name: Build LLVM

on:
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl xz-utils clang make cmake python3 zlib1g-dev ninja-build

      - name: Build LLVM
        run: make llvm
        
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvm-linux-x86_64
          path: lib/llvm/
          retention-days: 7

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-make
            mingw-w64-x86_64-tar
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-ninja
            git
          

      - name: Build LLVM
        shell: msys2 {0}
        run: |
          make llvm LLVM_BUILD_ARGS="-DZLIB_INCLUDE_DIR=/mingw64/include -DZLIB_LIBRARY=/mingw64/lib/libz.a"

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvm-windows-x86_64
          path: lib/llvm/
          retention-days: 7