name: Build LLVM

on:
  push:
    branches: [ master ]

jobs:
  build-linux:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl xz-utils clang make cmake python3 ninja-build libstdc++-14-dev

      - uses: actions/cache@v4
        with:
          path: lib/llvm-19.1.7
          key: linux-${{ matrix.arch }}-llvm-19.1.7

      - name: Build LLVM
        run: make libclang-full.a.gz LLVM_BUILD_ARGS="-DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache"
        env:
          SCCACHE_GHA_ENABLED: "true"
        
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvm-linux-${{ matrix.arch }}
          path: lib/llvm/
          retention-days: 7

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libclang-linux-${{ matrix.arch }}
          path: libclang-full.a.gz
          retention-days: 7

  build-macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
      
      - name: Install dependencies
        run: |
          brew install make ninja

      - uses: actions/cache@v4
        with:
          path: lib/llvm-19.1.7
          key: macos-arm64-llvm-19.1.7

      - name: Build LLVM
        run: >
          make libclang-full.a.gz LLVM_BUILD_ARGS="
          -DCMAKE_C_COMPILER_LAUNCHER=sccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache" TAR=gtar

        env:
          SCCACHE_GHA_ENABLED: "true"
        
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvm-macos-arm64
          path: lib/llvm/
          retention-days: 7
      
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libclang-macos-arm64
          path: libclang-full.a.gz
          retention-days: 7


  build-windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            make
            git
            tar
            gzip
            python

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
      
      - name: Configure sccache
        id: sccache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
            core.exportVariable('SCCACHE_PATH', process.env.SCCACHE_PATH || '');


      - uses: actions/cache@v4
        with:
          path: lib/llvm-19.1.7
          key: windows-x64-llvm-19.1.7

      - name: Build LLVM
        shell: msys2 {0}
        run: |
            SCCACHE_PATH_MSYS=$(cygpath "$SCCACHE_PATH")
            make libclang-full.a.gz LLVM_BUILD_ARGS="-DCMAKE_C_COMPILER_LAUNCHER=$SCCACHE_PATH_MSYS -DCMAKE_CXX_COMPILER_LAUNCHER=$SCCACHE_PATH_MSYS"
        env:
          SCCACHE_GHA_ENABLED: "true"

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llvm-windows-x64
          path: lib/llvm/
          retention-days: 7

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libclang-windows-x64
          path: libclang-full.a.gz
          retention-days: 7